# Generated by Django 5.1.6 on 2026-08-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(default='Johnny Carew Pole', max_length=120)),
                ('published_on', models.DateField()),
                ('excerpt', models.TextField(blank=True)),
                ('featured_on_home', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('sector', models.CharField(max_length=80)),
                ('head_office', models.CharField(max_length=80)),
                ('transaction_type', models.CharField(max_length=80)),
                ('invested_on', models.DateField()),
                ('status', models.CharField(choices=[('current', 'Current'), ('realised', 'Realised')], max_length=20)),
                ('summary', models.TextField()),
                ('quote', models.TextField(blank=True)),
                ('quote_attribution', models.CharField(blank=True, max_length=160)),
                ('featured_on_home', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=160)),
                ('bio', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
