# Generated by Django 5.1.6 on 2026-08-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='company_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='company_quote_attribution',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
