# Generated by Django 5.1.6 on 2026-08-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_portfoliocompany_company_quote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional caption shown on the homepage carousel.', max_length=160)),
                ('alt_text', models.CharField(help_text='Describe the image for accessibility.', max_length=160)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('link_url', models.CharField(blank=True, help_text='Optional link, e.g. /our-portfolio/ilektra/ or a full URL.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Homepage carousel slide',
                'verbose_name_plural': 'Homepage carousel slides',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
