# Generated by Django 5.1.6 on 2026-08-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homepageslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(blank=True, help_text='Full article. If blank, the excerpt is shown on the article page.'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, help_text='Hero and card image for this article.', upload_to='news/'),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='image',
            field=models.ImageField(blank=True, help_text='Hero and card image for this deal.', upload_to='portfolio/'),
        ),
    ]
