# Generated by Django 5.1.6 on 2026-08-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newsarticle_body_newsarticle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo, shown on portfolio cards and the deal page.', upload_to='portfolio/logos/'),
        ),
    ]
